### ISSUE TITLE
Support for more transforms?

### ISSUE THREAD

**Issue by abutterworth** [geowarin/electron-hot-loader#10]
Great work, I love this simplicity of this.  Digging through I'm not quite sure how I might add support for LESS or SCSS. Any thoughts?

**Comment by geowarin** [comment]
Hi @abutterworth. Thanks for your appreciation!

This project does not really load css.
There is just [one feature](https://github.com/geowarin/electron-hot-loader/blob/master/src/watchCss.js) that busts the css cache by adding a timestamp to the `<link href>` of the stylesheets.

It's already a bit out of place and I don't think adding more dependencies to the project would be such a great idea.

However, launching any preprocessor that can watch your sass or less files and compile them to css would do the job.
For instance, node-sass has a [watch-mode](https://github.com/sass/node-sass#usage-1).

You could use it simply as a job running in parallel of your app in development with something like [npm-run-all](https://www.npmjs.com/package/npm-run-all).
Or use [node's exec](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) to run it from your code.

What do you think ?
