### ISSUE TITLE
ES6 module support

### ISSUE THREAD

**Issue by konsumer** [geowarin/electron-hot-loader#12]
I am not getting any reloading. I used this in my index.js, like this to try to enable ES6:

``` js
const electronHot = require('electron-hot-loader')
electronHot.install()
electronHot.watchJsx(['app/**/*.jsx'])

require('babel-register')
require('./index.jsx')
```

I have a feeling they are both messing with how require works, and it's screwing things up. Is there a better way to get ES6 module support?

**Comment by geowarin** [comment]
Hi @konsumer.

You are right, babel-register and electron-hot-loader both use node require extensions. They are incompatible.

The [goal](https://github.com/geowarin/electron-hot-loader#goal) of electron hot loader is to provide hot reloading outside of webpack and babel.

With the latest versions of node and electron, you actually have access to pretty much all [ES6 features](http://node.green/) except the ES6 modules syntax.

Check out what's available in [bare electron](http://electron.atom.io/blog/2016/03/25/electron-37) and see if that fits your needs.

If ES6 modules are a must have, you shouldn't use electron-hot-loader but things like [browserify ](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate) or [webpack](https://github.com/chentsulin/electron-react-boilerplate).
